### ISSUE TITLE
picqer/moneybird-php-client outdated

### ISSUE THREAD

**Issue by DennisZwart** [casdr/laravel-moneybird#1]
Hello,

Can you update the picqer/moneybird-php-client version so 'due_date' is availeble 
(see https://github.com/picqer/moneybird-php-client/pull/93/files)
in/vendor/picqer/moneybird-php-client/src/Picqer/Financials/Moneybird/Entities/SalesInvoice.php

Sincerely Dennis

**Comment by casdr** [comment]
Hi,

v1.1.0 will use any version above 0.15.0.
